version: "3.8"
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  nest-app:
    build:
      context: /home/ubuntu/order-service-nest/nest-backend
    container_name: nest-app
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=airflow
      - DB_PASSWORD=airflow
      - DB_NAME=postgres
      - TZ=Asia/Jakarta
    volumes:
      - /home/ubuntu/order-service-nest/nest-backend:/app
      - /app/node_modules
      - /etc/localtime:/etc/localtime:ro
    command: npm run start:prod

  airflow-webserver:
    image: apache/airflow:2.5.0
    restart: always
    user: "root"
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__WORKERS: 2
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9090:8080"
    command: >
      bash -c "
      mkdir -p /opt/airflow/logs/scheduler &&
      chmod -R 777 /opt/airflow/logs &&
      airflow db upgrade &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
      airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.5.0
    restart: always
    user: "root"
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /etc/localtime:/etc/localtime:ro
    command: >
      bash -c "
      mkdir -p /opt/airflow/logs/scheduler &&
      chmod -R 777 /opt/airflow/logs &&
      airflow scheduler"

volumes:
  postgres-data:
